truck:
    parameter:
        jwt-expired: 5
        jwt-key: asdfSFS34wfsdfsdfSDSD32dfsddDDerQSNCK34SOWEK5354fdgdf4
server:
    port: 8089
spring:
    datasource:
        url: jdbc:mysql://168.231.93.145:3306/gymDB
        username: gym
        password: Gym2025.
    application:
        name: ms-truck
#    security:
#        user:
#            name: admin
#            password: admin2025

#    jpa:
#        show-sql: true
#        properties:
#            hibernate:
#                format_sql: true
#                use_sql_comments: true

#services:
#    Truck-Subscription-Key: gym

provider:
    whatsapp: twilio
    sms: twilio
    email: gmail
    flow: twilio

sendgrid:
    api:
        key: SENDGRID_API_KEY
    email:
        from: danielo.castros@gmail.com

gmail:
    host: smtp.gmail.com
    port: 587
    username: danielo.castros@gmail.com
    password: Q8FoD%2*lU
    from: danielo.castros@gmail.com


#logging:
#    level:
#        org.hibernate.SQL: DEBUG
#        org.hibernate.type.descriptor.sql.BasicBinder: TRACE